// data.js 파일 내용
export const summaryColumns = ['id', 'name']
export const detailedColumns = [
  'id',
  'name',
  'ingredient',
  'dosageForm',
  'effect',
  'classification',
]

// --- 2. 상세 데이터 (모든 35개 데이터) ---
export const detailedData = [
  {
    id: 101,
    name: '타이레놀정 500mg',
    ingredient: '아세트아미노펜',
    dosageForm: '정제',
    effect: '해열 및 통증 완화',
    classification: '비향정/비마약',
  },
  {
    id: 102,
    name: '베아제정',
    ingredient: '디아스타제, 리파제 등',
    dosageForm: '정제',
    effect: '소화 불량, 식욕 부진',
    classification: '비향정/비마약',
  },
  {
    id: 103,
    name: '후시딘 연고',
    ingredient: '퓨시드산나트륨',
    dosageForm: '연고',
    effect: '세균성 피부 감염, 상처 치료',
    classification: '비향정/비마약',
  },
  {
    id: 104,
    name: '액티피드 정',
    ingredient: '슈도에페드린, 트리프롤리딘',
    dosageForm: '정제',
    effect: '코감기, 알레르기 비염 증상 완화',
    classification: '비향정/비마약',
  },
  {
    id: 105,
    name: '가스활명수 큐액',
    ingredient: '현호색, 육계, 정향 등',
    dosageForm: '액제',
    effect: '소화 불량, 위부 팽만감',
    classification: '비향정/비마약',
  },
  {
    id: 106,
    name: '이지엔 6 이브 연질캡슐',
    ingredient: '이부프로펜, 파마브롬',
    dosageForm: '캡슐',
    effect: '생리통, 두통 등 각종 통증',
    classification: '비향정/비마약',
  },
  {
    id: 107,
    name: '마데카솔 케어 연고',
    ingredient: '센텔라 정량 추출물, 네오마이신',
    dosageForm: '연고',
    effect: '경미한 상처, 피부 궤양',
    classification: '비향정/비마약',
  },
  {
    id: 108,
    name: '판콜 에이 내복액',
    ingredient: '아세트아미노펜, dl-메틸에페드린',
    dosageForm: '액제',
    effect: '감기의 여러 증상 (콧물, 코막힘 등)',
    classification: '비향정/비마약',
  },
  {
    id: 109,
    name: '영양제(예시)',
    ingredient: '비타민 C, 아연',
    dosageForm: '정제',
    effect: '육체 피로, 비타민 보급',
    classification: '비향정/비마약',
  },
  {
    id: 110,
    name: '겔포스 엠 현탁액',
    ingredient: '인산알루미늄겔',
    dosageForm: '현탁액',
    effect: '위염, 위궤양에 따른 통증 완화',
    classification: '비향정/비마약',
  },
  {
    id: 111,
    name: '자나팜정 0.5mg',
    ingredient: '알프라졸람',
    dosageForm: '정제',
    effect: '불안장애, 공황장애 (향정신성)',
    classification: '향정신성',
  },
  {
    id: 112,
    name: '졸피드정 10mg',
    ingredient: '졸피뎀타르타르산염',
    dosageForm: '정제',
    effect: '불면증의 단기 치료 (향정신성)',
    classification: '향정신성',
  },
  {
    id: 113,
    name: '애드빌정',
    ingredient: '이부프로펜',
    dosageForm: '정제',
    effect: '해열, 진통, 소염',
    classification: '비향정/비마약',
  },
  {
    id: 114,
    name: '코데인정 (예시)',
    ingredient: '코데인',
    dosageForm: '정제',
    effect: '기침 진정, 통증 완화 (마약)',
    classification: '마약',
  },
  {
    id: 115,
    name: '가바펜틴 300mg',
    ingredient: '가바펜틴',
    dosageForm: '캡슐',
    effect: '간질 및 신경병증성 통증',
    classification: '비향정/비마약',
  },
  {
    id: 116,
    name: '디아제팜정 5mg',
    ingredient: '디아제팜',
    dosageForm: '정제',
    effect: '불안, 진정, 근육 이완 (향정신성)',
    classification: '향정신성',
  },
  {
    id: 117,
    name: '에페드린 주사액',
    ingredient: '에페드린',
    dosageForm: '주사액',
    effect: '저혈압 치료, 기관지 확장',
    classification: '비향정/비마약',
  },
  {
    id: 118,
    name: '메디키넷 서방캡슐',
    ingredient: '메틸페니데이트',
    dosageForm: '캡슐',
    effect: '주의력결핍과잉행동장애(ADHD) (향정신성)',
    classification: '향정신성',
  },
  {
    id: 119,
    name: '모르핀 주사액 (예시)',
    ingredient: '모르핀',
    dosageForm: '주사액',
    effect: '강력한 통증 완화 (마약)',
    classification: '마약',
  },
  {
    id: 120,
    name: '오메가3 연질캡슐',
    ingredient: '오메가-3 지방산',
    dosageForm: '캡슐',
    effect: '혈중 중성지방 감소, 건조한 눈 개선',
    classification: '비향정/비마약',
  },
  {
    id: 121,
    name: '플루옥세틴 캡슐',
    ingredient: '플루옥세틴',
    dosageForm: '캡슐',
    effect: '우울증, 강박 장애',
    classification: '비향정/비마약',
  },
  {
    id: 122,
    name: '프로포폴 주사 (예시)',
    ingredient: '프로포폴',
    dosageForm: '주사액',
    effect: '전신 마취, 진정 (향정신성)',
    classification: '향정신성',
  },
  {
    id: 123,
    name: '아트로핀 주사',
    ingredient: '아트로핀',
    dosageForm: '주사액',
    effect: '서맥, 마취 전 투약',
    classification: '비향정/비마약',
  },
  {
    id: 124,
    name: '옥시코돈정 (예시)',
    ingredient: '옥시코돈',
    dosageForm: '정제',
    effect: '중증 통증 조절 (마약)',
    classification: '마약',
  },
  {
    id: 125,
    name: '센시아 정',
    ingredient: '센텔라아시아티카 정량추출물',
    dosageForm: '정제',
    effect: '정맥 순환 개선',
    classification: '비향정/비마약',
  },
  {
    id: 126,
    name: '훼스탈골드정',
    ingredient: '판크레아틴, 비오디아스타제',
    dosageForm: '정제',
    effect: '소화 불량, 과식 (소화제)',
    classification: '비향정/비마약',
  },
  {
    id: 127,
    name: '게보린 정',
    ingredient: '이소프로필안티피린, 아세트아미노펜',
    dosageForm: '정제',
    effect: '두통, 치통, 생리통 (진통제)',
    classification: '비향정/비마약',
  },
  {
    id: 128,
    name: '판피린 큐액',
    ingredient: '아세트아미노펜, 클로르페니라민',
    dosageForm: '액제',
    effect: '감기의 제증상 (종합 감기약)',
    classification: '비향정/비마약',
  },
  {
    id: 129,
    name: '아로나민 골드 정',
    ingredient: '푸르설티아민 (활성 비타민 B1)',
    dosageForm: '정제',
    effect: '육체 피로, 신경통, 눈의 피로 (비타민제)',
    classification: '비향정/비마약',
  },
  {
    id: 130,
    name: '후시딘 연고',
    ingredient: '퓨시드산나트륨',
    dosageForm: '연고',
    effect: '세균성 피부 감염, 상처 치료',
    classification: '비향정/비마약',
  },
  {
    id: 131,
    name: '이지엔 6 애니 연질캡슐',
    ingredient: '이부프로펜',
    dosageForm: '캡슐',
    effect: '두통, 발열, 요통 (진통소염제)',
    classification: '비향정/비마약',
  },
  {
    id: 132,
    name: '겔포스 엠 현탁액',
    ingredient: '인산알루미늄겔',
    dosageForm: '현탁액',
    effect: '위산과다, 속쓰림, 위부불쾌감 (제산제)',
    classification: '비향정/비마약',
  },
  {
    id: 133,
    name: '액티넘 EX 플러스 정',
    ingredient: '푸르설티아민, 피리독신',
    dosageForm: '정제',
    effect: '어깨 결림, 요통, 눈의 피로 (비타민제)',
    classification: '비향정/비마약',
  },
  {
    id: 134,
    name: '베나치오 에프 액',
    ingredient: 'L-멘톨, 고추틴크',
    dosageForm: '액제',
    effect: '소화 불량, 복부 팽만감 (소화제)',
    classification: '비향정/비마약',
  },
  {
    id: 135,
    name: '케토톱 플라스타',
    ingredient: '케토프로펜',
    dosageForm: '첩부제 (파스)',
    effect: '관절염, 근육통, 외상 (국소 진통소염제)',
    classification: '비향정/비마약',
  },
  {
    id: 136,
    name: '뮤코졸 정',
    ingredient: '암브록솔염산염',
    dosageForm: '정제',
    effect: '가래 배출 곤란, 급/만성 호흡기 질환 (거담제)',
    classification: '비향정/비마약',
  },
  {
    id: 137,
    name: '마데카솔 케어 연고',
    ingredient: '센텔라 정량 추출물, 네오마이신',
    dosageForm: '연고',
    effect: '경미한 상처, 피부 궤양 보조 치료',
    classification: '비향정/비마약',
  },
  {
    id: 138,
    name: '테라플루 나이트 타임',
    ingredient: '아세트아미노펜, 페닐레프린',
    dosageForm: '산제 (분말)',
    effect: '밤 시간 감기 증상 완화 (종합 감기약)',
    classification: '비향정/비마약',
  },
  {
    id: 139,
    name: '레모나 산',
    ingredient: '아스코르브산 (비타민 C)',
    dosageForm: '산제 (분말)',
    effect: '기미, 주근깨 완화, 비타민 보급 (비타민제)',
    classification: '비향정/비마약',
  },
  {
    id: 140,
    name: '안티푸라민 연고',
    ingredient: 'L-멘톨, 살리실산메틸',
    dosageForm: '연고',
    effect: '타박상, 근육통, 벌레 물린 곳',
    classification: '비향정/비마약',
  },
]

// A. summaryData (detailedData에서 필요한 컬럼만 추출하여 생성)
export const summaryData = detailedData.map((item) => ({
  id: item.id,
  name: item.name,
  dosageForm: item.dosageForm,
  effect: item.effect.split('(')[0].trim(), // 효능에서 분류 정보는 제거하여 요약
}))
